In [ ]:
import pandas as pd
import random

In [ ]:
file_path = 'Airline Review/combined.csv'
review_factor_df = pd.read_csv(file_path, index_col=False)

In [ ]:
print(review_factor_df.shape)
review_factor_df.head()

(90281, 14)

,Airline,reviews_id,reviews_header,reviews,date,Satisfaction Rating,Check-in and boarding,Cleanliness,Customer service,Food and Beverage,In-flight Entertainment,Legroom,Seat comfort,Value for money
0,AA,617422147,Direct flight makes all the difference,I've started driving to CLT airport (we have a...,September 2018,5.0,5.0,5.0,5.0,4.0,3.0,3.0,3.0,5.0
1,AA,617420441,There's nothing special about Airline Travel t...,Let's start with the Group boarding assignment...,August 2018,3.0,2.0,3.0,3.0,3.0,4.0,3.0,4.0,4.0
2,AA,617420436,"Not absolutely terrible, but not great either",Uncomfortable seats and leg room wasn't great....,September 2018,3.0,5.0,5.0,3.0,NaN,1.0,3.0,1.0,3.0
3,AA,617420283,Poor experience,Very little space between seats. My seat would...,August 2018,1.0,3.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0
4,AA,617420023,American Airline flight experience,we had a good flight experience to our destina...,July 2018,4.0,5.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0

In [ ]:
review_factor_df[['Month', 'Year']] = review_factor_df['date'].str.split(' ', expand=True)


review_factor_df['Month'] = pd.to_datetime(review_factor_df['Month'], format='%B').dt.month
review_factor_df['Year'] = review_factor_df['Year'].astype(int)
review_factor_df.insert(2, 'date', review_factor_df.pop('date'))
review_factor_df.insert(3, 'Year', review_factor_df.pop('Year'))
review_factor_df.insert(4, 'Month', review_factor_df.pop('Month'))

In [ ]:
review_factor_df['Quarter'] = pd.cut(review_factor_df['Month'], bins=[1, 4, 7, 10, 13], labels=[1, 2, 3, 4], right=False)
review_factor_df.insert(4, 'Quarter', review_factor_df.pop('Quarter'))

In [ ]:
review_factor_df

,Airline,reviews_id,date,Year,Quarter,Month,reviews_header,reviews,Satisfaction Rating,Check-in and boarding,Cleanliness,Customer service,Food and Beverage,In-flight Entertainment,Legroom,Seat comfort,Value for money
0,AA,617422147,September 2018,2018,3,9,Direct flight makes all the difference,I've started driving to CLT airport (we have a...,5.0,5.0,5.0,5.0,4.0,3.0,3.0,3.0,5.0
1,AA,617420441,August 2018,2018,3,8,There's nothing special about Airline Travel t...,Let's start with the Group boarding assignment...,3.0,2.0,3.0,3.0,3.0,4.0,3.0,4.0,4.0
2,AA,617420436,September 2018,2018,3,9,"Not absolutely terrible, but not great either",Uncomfortable seats and leg room wasn't great....,3.0,5.0,5.0,3.0,NaN,1.0,3.0,1.0,3.0
3,AA,617420283,August 2018,2018,3,8,Poor experience,Very little space between seats. My seat would...,1.0,3.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0
4,AA,617420023,July 2018,2018,3,7,American Airline flight experience,we had a good flight experience to our destina...,4.0,5.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90276,DL,518580767,August 2017,2017,3,8,No hassles. Arrived early. No complaints.,The flight was smooth and 40 minutes shorter t...,5.0,5.0,4.0,3.0,3.0,1.0,4.0,4.0,4.0
90277,DL,518580746,June 2017,2017,2,6,Round trip Cincinnati to Orlando,We flew economy plus both ways and had a great...,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,3.0
90278,DL,518580611,August 2017,2017,3,8,Delta gets it right,We flew Delta to Tennesse to see the solar ecl...,5.0,5.0,5.0,5.0,NaN,4.0,5.0,4.0,4.0
90279,DL,518580524,August 2017,2017,3,8,"Good experience, flights were on time.",Flights were on time and crew was nice and fri...,4.0,4.0,3.0,4.0,3.0,5.0,4.0,4.0,4.0
90280,DL,518580487,July 2017,2017,3,7,Delta Team,Flights were on time and fully booked. Loading...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0

In [ ]:
review_factor_df['Year'].value_counts()

2018    40187
2019    27002
2017    22400
2016      512
2020      177
2561        2
2562        1
Name: Year, dtype: int64

In [ ]:
review_factor_df['Month'].value_counts()

8     11131
9      8342
6      7926
7      7851
12     7770
11     7720
3      7097
10     7055
5      6847
2      6389
4      6201
1      5952
Name: Month, dtype: int64

In [ ]:
year_filtered_df = review_factor_df[review_factor_df['Year'].isin([2017, 2018, 2019])]
year_filtered_df

,Airline,reviews_id,date,Year,Quarter,Month,reviews_header,reviews,Satisfaction Rating,Check-in and boarding,Cleanliness,Customer service,Food and Beverage,In-flight Entertainment,Legroom,Seat comfort,Value for money
0,AA,617422147,September 2018,2018,3,9,Direct flight makes all the difference,I've started driving to CLT airport (we have a...,5.0,5.0,5.0,5.0,4.0,3.0,3.0,3.0,5.0
1,AA,617420441,August 2018,2018,3,8,There's nothing special about Airline Travel t...,Let's start with the Group boarding assignment...,3.0,2.0,3.0,3.0,3.0,4.0,3.0,4.0,4.0
2,AA,617420436,September 2018,2018,3,9,"Not absolutely terrible, but not great either",Uncomfortable seats and leg room wasn't great....,3.0,5.0,5.0,3.0,NaN,1.0,3.0,1.0,3.0
3,AA,617420283,August 2018,2018,3,8,Poor experience,Very little space between seats. My seat would...,1.0,3.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0
4,AA,617420023,July 2018,2018,3,7,American Airline flight experience,we had a good flight experience to our destina...,4.0,5.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90276,DL,518580767,August 2017,2017,3,8,No hassles. Arrived early. No complaints.,The flight was smooth and 40 minutes shorter t...,5.0,5.0,4.0,3.0,3.0,1.0,4.0,4.0,4.0
90277,DL,518580746,June 2017,2017,2,6,Round trip Cincinnati to Orlando,We flew economy plus both ways and had a great...,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,3.0
90278,DL,518580611,August 2017,2017,3,8,Delta gets it right,We flew Delta to Tennesse to see the solar ecl...,5.0,5.0,5.0,5.0,NaN,4.0,5.0,4.0,4.0
90279,DL,518580524,August 2017,2017,3,8,"Good experience, flights were on time.",Flights were on time and crew was nice and fri...,4.0,4.0,3.0,4.0,3.0,5.0,4.0,4.0,4.0
90280,DL,518580487,July 2017,2017,3,7,Delta Team,Flights were on time and fully booked. Loading...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0

In [ ]:
year_filtered_df['Year'].value_counts()

2018    40187
2019    27002
2017    22400
Name: Year, dtype: int64

In [ ]:
null_counts = year_filtered_df.isnull().sum()
null_counts

Airline                        0
reviews_id                     0
date                           0
Year                           0
Quarter                        0
Month                          0
reviews_header                 1
reviews                        0
Satisfaction Rating            0
Check-in and boarding      11962
Cleanliness                12218
Customer service            1393
Food and Beverage          13773
In-flight Entertainment     7460
Legroom                     1599
Seat comfort                1467
Value for money             3008
dtype: int64

In [ ]:
cleaned_df =  year_filtered_df.dropna()
cleaned_df.reset_index(drop=True, inplace=True)
cleaned_df.shape

(67968, 17)

In [ ]:
cleaned_df.isnull().any()

Airline                    False
reviews_id                 False
date                       False
Year                       False
Quarter                    False
Month                      False
reviews_header             False
reviews                    False
Satisfaction Rating        False
Check-in and boarding      False
Cleanliness                False
Customer service           False
Food and Beverage          False
In-flight Entertainment    False
Legroom                    False
Seat comfort               False
Value for money            False
dtype: bool

In [ ]:
cleaned_df[['Airline']].value_counts()

Airline
AA         25492
DL         24961
UA         17515
dtype: int64

In [ ]:
cleaned_df[['Airline', 'Year']].value_counts()

Airline  Year
DL       2018    11173
AA       2018    10565
UA       2018     8097
AA       2019     7945
DL       2019     7025
AA       2017     6982
DL       2017     6763
UA       2019     5845
         2017     3573
dtype: int64

In [ ]:
cleaned_df

,Airline,reviews_id,date,Year,Quarter,Month,reviews_header,reviews,Satisfaction Rating,Check-in and boarding,Cleanliness,Customer service,Food and Beverage,In-flight Entertainment,Legroom,Seat comfort,Value for money
0,AA,617422147,September 2018,2018,3,9,Direct flight makes all the difference,I've started driving to CLT airport (we have a...,5.0,5.0,5.0,5.0,4.0,3.0,3.0,3.0,5.0
1,AA,617420441,August 2018,2018,3,8,There's nothing special about Airline Travel t...,Let's start with the Group boarding assignment...,3.0,2.0,3.0,3.0,3.0,4.0,3.0,4.0,4.0
2,AA,617420283,August 2018,2018,3,8,Poor experience,Very little space between seats. My seat would...,1.0,3.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0
3,AA,617420023,July 2018,2018,3,7,American Airline flight experience,we had a good flight experience to our destina...,4.0,5.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0
4,AA,617418697,April 2018,2018,2,4,April 1st Santa Fe flight,Plane was larger than I expected and that was ...,4.0,4.0,4.0,4.0,3.0,1.0,3.0,4.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67963,DL,518580858,August 2017,2017,3,8,Excellent flight but I miss the outlets on Del...,Good flight from ORD to MSP. Crew was polite a...,5.0,5.0,5.0,4.0,3.0,3.0,3.0,4.0,4.0
67964,DL,518580767,August 2017,2017,3,8,No hassles. Arrived early. No complaints.,The flight was smooth and 40 minutes shorter t...,5.0,5.0,4.0,3.0,3.0,1.0,4.0,4.0,4.0
67965,DL,518580746,June 2017,2017,2,6,Round trip Cincinnati to Orlando,We flew economy plus both ways and had a great...,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,3.0
67966,DL,518580524,August 2017,2017,3,8,"Good experience, flights were on time.",Flights were on time and crew was nice and fri...,4.0,4.0,3.0,4.0,3.0,5.0,4.0,4.0,4.0
67967,DL,518580487,July 2017,2017,3,7,Delta Team,Flights were on time and fully booked. Loading...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0

In [ ]:
cleaned_df.to_csv('Airline Review/cleaned_review_factor.csv', index=False)

In [ ]:
review_factor_df = pd.read_csv('E:\zx/cleaned_review_factor.csv')
review_factor_df

,Airline,reviews_id,date,Year,Quarter,Month,reviews_header,reviews,Satisfaction Rating,Check-in and boarding,Cleanliness,Customer service,Food and Beverage,In-flight Entertainment,Legroom,Seat comfort,Value for money
0,AA,617422147,September 2018,2018,3,9,Direct flight makes all the difference,I've started driving to CLT airport (we have a...,5.0,5.0,5.0,5.0,4.0,3.0,3.0,3.0,5.0
1,AA,617420441,August 2018,2018,3,8,There's nothing special about Airline Travel t...,Let's start with the Group boarding assignment...,3.0,2.0,3.0,3.0,3.0,4.0,3.0,4.0,4.0
2,AA,617420283,August 2018,2018,3,8,Poor experience,Very little space between seats. My seat would...,1.0,3.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0
3,AA,617420023,July 2018,2018,3,7,American Airline flight experience,we had a good flight experience to our destina...,4.0,5.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0
4,AA,617418697,April 2018,2018,2,4,April 1st Santa Fe flight,Plane was larger than I expected and that was ...,4.0,4.0,4.0,4.0,3.0,1.0,3.0,4.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67963,DL,518580858,August 2017,2017,3,8,Excellent flight but I miss the outlets on Del...,Good flight from ORD to MSP. Crew was polite a...,5.0,5.0,5.0,4.0,3.0,3.0,3.0,4.0,4.0
67964,DL,518580767,August 2017,2017,3,8,No hassles. Arrived early. No complaints.,The flight was smooth and 40 minutes shorter t...,5.0,5.0,4.0,3.0,3.0,1.0,4.0,4.0,4.0
67965,DL,518580746,June 2017,2017,2,6,Round trip Cincinnati to Orlando,We flew economy plus both ways and had a great...,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,3.0
67966,DL,518580524,August 2017,2017,3,8,"Good experience, flights were on time.",Flights were on time and crew was nice and fri...,4.0,4.0,3.0,4.0,3.0,5.0,4.0,4.0,4.0
67967,DL,518580487,July 2017,2017,3,7,Delta Team,Flights were on time and fully booked. Loading...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0

In [ ]:
grouped = review_factor_df.groupby(['Airline', 'Year', 'Quarter']).size().reset_index(name='len')
result = grouped.to_dict(orient='records')
result

[{'Airline': 'AA', 'Year': 2017, 'Quarter': 1, 'len': 272},
 {'Airline': 'AA', 'Year': 2017, 'Quarter': 2, 'len': 1443},
 {'Airline': 'AA', 'Year': 2017, 'Quarter': 3, 'len': 3052},
 {'Airline': 'AA', 'Year': 2017, 'Quarter': 4, 'len': 2215},
 {'Airline': 'AA', 'Year': 2018, 'Quarter': 1, 'len': 2679},
 {'Airline': 'AA', 'Year': 2018, 'Quarter': 2, 'len': 2813},
 {'Airline': 'AA', 'Year': 2018, 'Quarter': 3, 'len': 2855},
 {'Airline': 'AA', 'Year': 2018, 'Quarter': 4, 'len': 2218},
 {'Airline': 'AA', 'Year': 2019, 'Quarter': 1, 'len': 2001},
 {'Airline': 'AA', 'Year': 2019, 'Quarter': 2, 'len': 2395},
 {'Airline': 'AA', 'Year': 2019, 'Quarter': 3, 'len': 2077},
 {'Airline': 'AA', 'Year': 2019, 'Quarter': 4, 'len': 1472},
 {'Airline': 'DL', 'Year': 2017, 'Quarter': 1, 'len': 223},
 {'Airline': 'DL', 'Year': 2017, 'Quarter': 2, 'len': 713},
 {'Airline': 'DL', 'Year': 2017, 'Quarter': 3, 'len': 2671},
 {'Airline': 'DL', 'Year': 2017, 'Quarter': 4, 'len': 3156},
 {'Airline': 'DL', 'Year': 2018, 'Quarter': 1, 'len': 4020},
 {'Airline': 'DL', 'Year': 2018, 'Quarter': 2, 'len': 2459},
 {'Airline': 'DL', 'Year': 2018, 'Quarter': 3, 'len': 2749},
 {'Airline': 'DL', 'Year': 2018, 'Quarter': 4, 'len': 1945},
 {'Airline': 'DL', 'Year': 2019, 'Quarter': 1, 'len': 1623},
 {'Airline': 'DL', 'Year': 2019, 'Quarter': 2, 'len': 2118},
 {'Airline': 'DL', 'Year': 2019, 'Quarter': 3, 'len': 2049},
 {'Airline': 'DL', 'Year': 2019, 'Quarter': 4, 'len': 1235},
 {'Airline': 'UA', 'Year': 2017, 'Quarter': 1, 'len': 121},
 {'Airline': 'UA', 'Year': 2017, 'Quarter': 2, 'len': 341},
 {'Airline': 'UA', 'Year': 2017, 'Quarter': 3, 'len': 1384},
 {'Airline': 'UA', 'Year': 2017, 'Quarter': 4, 'len': 1727},
 {'Airline': 'UA', 'Year': 2018, 'Quarter': 1, 'len': 2004},
 {'Airline': 'UA', 'Year': 2018, 'Quarter': 2, 'len': 2101},
 {'Airline': 'UA', 'Year': 2018, 'Quarter': 3, 'len': 2287},
 {'Airline': 'UA', 'Year': 2018, 'Quarter': 4, 'len': 1705},
 {'Airline': 'UA', 'Year': 2019, 'Quarter': 1, 'len': 1430},
 {'Airline': 'UA', 'Year': 2019, 'Quarter': 2, 'len': 1654},
 {'Airline': 'UA', 'Year': 2019, 'Quarter': 3, 'len': 1647},
 {'Airline': 'UA', 'Year': 2019, 'Quarter': 4, 'len': 1114}]

In [ ]:
zowie_df = pd.read_csv('E:\zx/zowie_combined.csv')
zowie_df.shape

(53666898, 42)

In [ ]:
zowie_df = zowie_df.rename(columns={'TkCarrier': 'Airline'})

In [ ]:
zowie_df.head()

,ItinID,MktID,MktCoupons,Year,Quarter,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCountry,...,BulkFare,Passengers,MktFare,MktDistance,MktDistanceGroup,MktMilesFlown,NonStopMiles,ItinGeoType,MktGeoType,Unnamed: 41
0,201714497723,20171449772301,1,2017,1,14107,1410702,30466,PHX,US,...,0.0,1.0,136.0,325.0,1,325.0,325.0,2,2,NaN
1,201714497724,20171449772401,1,2017,1,14107,1410702,30466,PHX,US,...,0.0,2.0,153.0,325.0,1,325.0,325.0,2,2,NaN
2,201714497725,20171449772501,1,2017,1,14107,1410702,30466,PHX,US,...,0.0,1.0,155.0,325.0,1,325.0,325.0,2,2,NaN
3,201714497726,20171449772601,1,2017,1,14107,1410702,30466,PHX,US,...,0.0,1.0,156.0,325.0,1,325.0,325.0,2,2,NaN
4,201714497727,20171449772701,1,2017,1,14107,1410702,30466,PHX,US,...,0.0,8.0,163.0,325.0,1,325.0,325.0,2,2,NaN

In [ ]:
# Iterate over each dictionary and remove rows randomly until the desired length is achieved
for attr in result:
    filtered_df = zowie_df[(zowie_df['Airline'] == attr['Airline']) & (zowie_df['Year'] == attr['Year']) & (zowie_df['Quarter'] == attr['Quarter'])]
    if len(filtered_df) > attr['len']:
        remove_indices = random.sample(list(filtered_df.index), len(filtered_df) - attr['len'])
        zowie_df.drop(remove_indices, inplace=True)

In [ ]:
zowie_df.shape

(67968, 42)

In [ ]:
zowie_df.reset_index(drop=True, inplace=True)
zowie_df

,ItinID,MktID,MktCoupons,Year,Quarter,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCountry,...,BulkFare,Passengers,MktFare,MktDistance,MktDistanceGroup,MktMilesFlown,NonStopMiles,ItinGeoType,MktGeoType,Unnamed: 41
0,201714498403,20171449840302,1,2017,1,14698,1469802,34236,SBP,US,...,0.0,1.0,101.00,509.0,2,509.0,509.0,2,2,NaN
1,201714498658,20171449865804,2,2017,1,12191,1219102,31453,HOU,US,...,0.0,1.0,292.66,919.0,2,919.0,822.0,2,2,NaN
2,201714501901,20171450190102,1,2017,1,14107,1410702,30466,PHX,US,...,0.0,2.0,110.50,261.0,1,261.0,261.0,2,2,NaN
3,201714510542,20171451054203,2,2017,1,12511,1251102,32511,JLN,US,...,0.0,1.0,333.50,1060.0,3,1060.0,485.0,2,2,NaN
4,201714514133,20171451413301,2,2017,1,15376,1537602,30436,TUS,US,...,0.0,1.0,327.50,712.0,2,712.0,639.0,2,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67963,201844110753,20184411075302,1,2018,4,12889,1288903,32211,LAS,US,...,0.0,1.0,104.00,1222.0,3,1222.0,1222.0,2,2,NaN
67964,201844111206,20184411120601,1,2018,4,12266,1226603,31453,IAH,US,...,0.0,1.0,351.00,1222.0,3,1222.0,1222.0,2,2,NaN
67965,201844111658,20184411165801,1,2018,4,12266,1226603,31453,IAH,US,...,0.0,1.0,178.00,1379.0,3,1379.0,1379.0,2,2,NaN
67966,201844113290,20184411329001,2,2018,4,12266,1226603,31453,IAH,US,...,0.0,1.0,42.00,1716.0,4,1716.0,1635.0,2,2,NaN
67967,201844114595,20184411459501,1,2018,4,12266,1226603,31453,IAH,US,...,0.0,1.0,598.00,1416.0,3,1416.0,1416.0,2,2,NaN

In [ ]:
zowie_df['Airline'].unique()

array(['AA', 'DL', 'UA'], dtype=object)

In [ ]:
zowie_df['Airline'].value_counts()

Airline
AA    25492
DL    24961
UA    17515
Name: count, dtype: int64

In [ ]:
zowie_df.to_csv('filtered_zowie.csv', index=False)

In [ ]:
merged_review_factor_zowie = pd.merge(review_factor_df, zowie_df, on=['Airline', 'Year', 'Quarter'])
merged_review_factor_zowie

MemoryError: Unable to allocate 10.4 GiB for an array with shape (9, 155132660) and data type float64

In [ ]:
filt = [
    {
        "airline": "AA"

     }
]